version: '3.3'

services:
  wordpress:
    build: .
    depends_on:
      - db
    volumes:
      - .:/var/www/html/wp-content/plugins/endlinex-cookie
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      # Admin účet
      WORDPRESS_ADMIN_USERNAME: admin
      WORDPRESS_ADMIN_PASSWORD: 001001
      WORDPRESS_ADMIN_EMAIL: info@patrikvadura.cz
      WORDPRESS_DEBUG: 1

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  wordpress_data: {}
  db_data: {}